name: Deploy content from react to Pages

on:  
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: |
          cd react-sudoku 
          npm ci
      - name: Create build directory
        run: |
          cd react-sudoku
          npm run build --if-present

  # deploy:
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v3
    #   runs: 
    #     using: 'composite'
    #     steps: 
    #       - run : npm ci
    #         shell: bash        





