# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  
  push:
    branches: ["main"]

  
jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        





